### ISSUE TITLE
Problem with single quote using whereEncrypted...

### ISSUE THREAD

**Issue by kirame09** [elgibor-solution/laravel-database-encryption#10]
This is prone for sql injection. Can I make PR for this issue?

**Comment by kirame09** [comment]
I can be a contributor for this package and I can also maintain and improve this and fix issues.
I was trying to push and make PR to this package but it seems like this is not permitted. 

Let me know your thoughts.

**Comment by elgibor-solution** [comment]
@kirame09 Hi, I already invite you as contributor for this package
