### ISSUE TITLE
Not using Crypt

### ISSUE THREAD

**Issue by mellester** [elgibor-solution/laravel-database-encryption#5]
Looking at the source code you directly implement your own Encrypted class. 
Whilst the readme says your are using the Crypt class
This class does not use a initialization vector so therefore is less secure than they default Crypt class from Laravel.
In short this means duplicate values will have the same value in the database

**Comment by elgibor-solution** [comment]
Hi @mellester 

Yeah, If use crypt then i can't run search query. Feel free to do PR if you have a better idea..
